### ISSUE TITLE
Make an RFC for Notebook mode in DrR or Jypyter.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus-brainstorming#100]
DrRacket notebook mode (like Jupyter) or hooks to support integration with Jupyter and similar products/

I raised it because it seems like notebook mode support is important in any new language. I *think* this doubly true for LOP where the intent is to have multiple interoperable languages co-existing?

--
Previous discussion on DrRacket Notebook Mode and the existing IPython/Jupyter kernel include: 

- 2018-12-20  <https://groups.google.com/forum/#!topic/racket-users/MsAh2aBU5Sw> 
- 2019-06-26 <https://groups.google.com/d/msg/racket-users/XQXYxtCM2-k/AbTTqMqlAgAJ>  
- 2019-07-24 <https://groups.google.com/d/msg/racket-users/XQXYxtCM2-k/C97eRavaBQAJ>

--

**Comment by MarcKaufmann** [comment]
Not just for LOP, but also anything to do with data science would benefit from this.

**Comment by spdegabrielle** [comment]
@Marckaufmann this should be moved to [racket/DrRacket](/racket/rrracket)

**Comment by MarcKaufmann** [comment]
The RFC or my comment?

**Comment by spdegabrielle** [comment]
moved to https://github.com/racket/drracket/issues/311 as DrRacket features are not the purpose of this repo

**Comment by MarcKaufmann** [comment]
I see, fair enough.
