### ISSUE TITLE
Reconsider the name "Racket 2"

### ISSUE THREAD

**Issue by khinsen** [racket/rhombus-brainstorming#111]
It is often said that naming is one of the hard problems in computer science. This also applies to naming languages. Therefore I propose to reconsider the name "Racket 2" before it is too late.

Reason #1: confusion. I just installed Racket 7.4 on my computer, and now I participate in a discussion about Racket 2. I have been around for long enough to know that "Racket" means both an environment for designing languages and the current principal language in that environment, but I guess that's much less obvious for newcomers. This could be a good occasion to remove that confusion.

Reason #2: expectations. Anyone who has some experience with software but little experience with Racket will expect that "Racket 2" is an essentially compatible improvement on "Racket 1" which renders "Racket 1" obsolete. For a historical precedent, check the Python 2->3 transition, which has generated a lot of pain for many people, one reason being the implicit expectation of "better in every respect" and "mostly a drop-in replacement" associated with a version number increase.

**Comment by jackfirth** [comment]
Relevant [prior statements](https://groups.google.com/forum/#!msg/racket-users/HiC7z3A5O-k/XPR2wbSJCQAJ) from Matthew Flatt about the name "Racket 2":

> Although we could literally write `#lang racket2` for modules in the
new language, "Racket2" is normally understood as a placeholder for a
more distinct name. As a matter of branding, perhaps the language would
be called "Racket X" for some good X --- shortened to "X" in some
contexts --- and Racket X program would be written with `#lang X` line
at the top. Maybe the name depends on how different Racket2 turns out
to be from Racket, so it makes sense to pick a name later.

**Comment by evelynmitchell** [comment]
Please pick a name for the new, which is distinct from Racket.
An unrelated name, creates room for experiment, without confusion on the 
part of those who are using Racket.

**Comment by otherjoel** [comment]
Related reading, published yesterday: [Is Perl 6 Being Renamed?](http://blogs.perl.org/users/ovid/2019/08/is-perl-6-being-renamed.html)

**Comment by jackfirth** [comment]
@evelynmitchell We would like to. Would anyone like to open a pull request with a list of name suggestions?

**Comment by tgbugs** [comment]
Names that I have seen or used:
1. rhombus
1. covin
1. trapezoidal
1. kerfuffle
1. clatter (already in use)
1. heist (already in use)

**Comment by AlQuemiste** [comment]
I think the new name should be unique, and also remind us of Lisp somehow; so, I'd suggest
 “Lyric” or “Lyrik”. 
It imlplicates the poetical beauties of Lisp and its descendants. It has a vague taste of Lisp in the first and that of “racket” in the second syllable.

**Comment by mbutterick** [comment]
> "Racket2" is normally understood as a placeholder for a
more distinct name. As a matter of branding, perhaps the language would
be called "Racket X" for some good X --- shortened to "X" in some
contexts --- and Racket X program would be written with #lang X line
at the top.

I can believe that “Racket2” is the name of something that existing Racketeers can distinguish, with small effort, from “Racket”. 

I am less persuaded that people new to this community — who are a key market for this new language — will discern the difference as easily. To them, “Racket2” simply sounds like the successor to “Racket”. If you already believed (for whatever rational or irrational reason) that you didn’t like Racket, why would you be interested in Racket2? It would be like broccoli farmers trying to appeal to children by calling it Broccoli2. Press release: “Broccoli2 now tastes like french fries!” Sorry — you lost them at broccoli.

Again, if this were some private project, it wouldn’t matter. But the development of Racket2 will be happening in public view, assumedly in part to attract some of those people who had given Racket the brush-off in the past. So I end up thinking that a name other than “Racket2” makes more sense. To those newly curious, the genetic connection to Racket is not especially interesting. They’ll be evaluating this new language on its own merits.

To use a practical analogy: this new language will be at least as different from current Racket as Scribble is, and Scribble warranted its own name. It’s just ”Scribble” — not “Racket Scribble” or “Scribble by Racket”, etc.

**Comment by mbutterick** [comment]
(And in light of #119, maybe `sapling` has potential)

**Comment by spdegabrielle** [comment]
Please close this issue - resolved.
