### ISSUE TITLE
Concurrency and parallelism improvements after chezsheme 

### ISSUE THREAD

**Issue by bijang** [racket/rhombus-brainstorming#160]
Now that chez scheme is in place, is there room to improve, make more fine grained and sophisticated, the concurrency and parallelism of racket? (I understand this is very nonspecific suggestion)

**Comment by samth** [comment]
First, I don't think this repository is really the right place for this issue -- this repository is about Rhombus specifically.

On the particular issue, there are already some parallelism improvements -- for example, much more of the runtime is future-safe. Figuring out more ways to reduce the footprint of places, making more components future-safe, and generally increasing scalability is always a good thing but there isn't something immediate that Chez enables.
