### ISSUE TITLE
Make a RFC about DrRacket2

### ISSUE THREAD

**Issue by spdegabrielle** [racket/rhombus-brainstorming#96]
Is a DrRacket2 needed?
Who is it for?
What functionality should it have?
What should it look like?

**Comment by spdegabrielle** [comment]
Suggestion: Notebook Mode like Jupyter Notebooks

**Comment by spdegabrielle** [comment]
Suggestion: sidebar -  a core part of any IDE but is conspicuously missing from DrRacket. 

1. The (define ...) button which provides the overview functionality that is often in sidebars of other IDEs. I'd suggest that moving this to a sidebar is more familiar UI than the current popup
2. filesystem view sidebar mode: There also is a plugin adds this to DrRACKET1: https://github.com/MatrixForChange/files-viewer
3. package view sidebar mode- using `info.rkt` (`#lang info`) files as the source

**Comment by spdegabrielle** [comment]
keyword lookup while you type is ON by default
but easy to turn off/on

**Comment by spdegabrielle** [comment]
signature (blue bubble/box) on by default 
but easy to turn off/on

**Comment by Nyanraltotlapun** [comment]
Broad use of multi threading(os threads). For background expansion, for auto completion, for everything basically so that the GUI does not lag.
Repl also must be separated (in separate thread) from editor.

**Comment by hidaris** [comment]
I think notebook mode like [Glamorous Toolkit](https://gtoolkit.com/) is more worth looking forward to.

**Comment by spdegabrielle** [comment]
https://github.com/racket/racket2-rfcs/issues/96#issuecomment-517796591 @hidaris GT seems different in that is isn't cells based? Do I have that right? Like you are actually using a notebook!

**Comment by spdegabrielle** [comment]
projectional editing ? (Like jetbrains MPS)

**Comment by spdegabrielle** [comment]
Closing this issue.

DrRacket changes should be raised against https://github.com/racket/drracket

I have moved the issues raised here to https://github.com/racket/drracket

Stephen

**Comment by gus-massa** [comment]
Perhaps it's too early, but if the new syntax uses some special characters like `|` that trigger special indentation and edition, it will be necessary to add support in DrRacket (and preferably in other popular editors too). But I think it's better to wait until the new syntax is stabilized.
